[package]
name = "tuimodplayer"
version = "0.1.0"
authors = ["Kunshan Wang <wks1986@gmail.com>"]
edition = "2021"
description = "A text-user-interface module music player using libopenmpt"
license = "GPL-3.0"

[dependencies]
openmpt = "0.3.1"
cpal = { version = "0.13.5" }
rodio = { version = "0.15.0", default-features = false }
anyhow = "1.0.56"
zip = "0.6.2"
clap = { version = "3.1.8", features = ["derive"] }
tui = "0.17.0"
crossterm = "0.23.2"
atomic = "0.5.1"
log = { version = "0.4.16", features = ["std"] }
lazy_static = "1.4.0"
walkdir = "2"
